import { v4 as uuid } from 'uuid';

export default [
  {
    id: 1,
    firstname: 'Tosin',
    lastname: 'OluwaTimi',
    email: 'tosin.oluwatimi@gmail.com',
    username: 'tosin_oluwatimi',
    phone: '08147385920',
    createdAt: new Date("2021-04-10"),
    updatedAt: new Date(),
    promoCode: 'neo0001',
    customerPaid: 'Yes',
    followUpEmailSent: 'No',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'Yes',
    nutritionalAssesment: 'completed',
    remark: "Remarks about customer",
  },
  {
    id: 2,
    firstname: 'Ade',
    lastname: 'Opeyimipo',
    email: 'ade.opeyemipo@gmail.com',
    username: 'ade_opeyemipo',
    phone: '08141394403',
    createdAt: new Date("2021-04-12T13:00:00"),
    updatedAt: new Date(),
    promoCode: 'neo0002',
    customerPaid: 'No',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'No',
    nutritionistScheduled: 'Yes',
    nutritionalAssesment: 'pending',
    remark: "Remarks about customer",
  },
  {
    id: 3,
    firstname: 'Chuks',
    lastname: 'Okoye',
    email: 'chuks.okoye@yahoo.com',
    username: 'chuks_okoye',
    phone: '080149850482',
    createdAt: new Date("2021-03-25T10:15:00"),
    updatedAt: new Date(),
    promoCode: 'neo0003',
    customerPaid: 'Yes',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'Yes',
    nutritionalAssesment: 'completed',
    remark: "Remarks about customer",
  },
  {
    id: 4,
    firstname: 'Musa',
    lastname: 'Adamu',
    email: 'musa.adamu@yahoo.com',
    username: 'musa_adamu',
    phone: '080149850482',
    createdAt: new Date("2021-03-20T09:35:00"),
    updatedAt: new Date(),
    promoCode: 'neo0004',
    customerPaid: 'No',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'No',
    nutritionistScheduled: 'Yes',
    nutritionalAssesment: 'missing',
    remark: "Remarks about customer",
  },
  {
    id: 5,
    firstname: 'Tega',
    lastname: 'Okez',
    email: 'tega.okez@gamil.com',
    username: 'tega_okez',
    phone: '08083339812',
    createdAt: new Date("2021-04-16T13:45:00"),
    updatedAt: new Date(),
    promoCode: 'neo0005',
    customerPaid: 'Yes',
    followUpEmailSent: 'No',
    followUpCallSent: 'No',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'pending',
    remark: "Remarks about customer",
  },
  {
    id: 6,
    firstname: 'Timi',
    lastname: 'Omotosho',
    email: 'timi.omotosho@gamil.com',
    username: 'timi_omotosho',
    phone: '08082219812',
    createdAt: new Date("2021-04-18T16:00:00"),
    updatedAt: new Date(),
    promoCode: 'neo0006',
    customerPaid: 'Yes',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'No',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'completed',
    remark: "Remarks about customer",
  },
  {
    id: 7,
    firstname: 'George',
    lastname: 'Stan',
    email: 'georgestan@gamil.com',
    username: 'george_stan',
    phone: '08134362783',
    createdAt: new Date("2021-04-06T11:45:00"),
    updatedAt: new Date(),
    promoCode: 'neo0007',
    customerPaid: 'No',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'missing',
    remark: "Remarks about customer",
  },
  {
    id: 8,
    firstname: 'Yusuf',
    lastname: 'Shittu',
    email: 'yusuf.shittu@gamil.com',
    username: 'yusuf_shittu',
    phone: '08045532264',
    createdAt: new Date("2021-04-11T12:15:00"),
    updatedAt: new Date(),
    promoCode: 'neo0008',
    customerPaid: 'Yes',
    followUpEmailSent: 'No',
    followUpCallSent: 'No',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'completed',
    remark: "Remarks about customer",
  },
  {
    id: 9,
    firstname: 'Nimah',
    lastname: 'Shittu',
    email: 'Nimah.shittu@gamil.com',
    username: 'Nimah_shittu',
    phone: '08177733082',
    createdAt: new Date("2021-04-15T16:00:00"),
    updatedAt: new Date(),
    promoCode: 'neo0009',
    customerPaid: 'No',
    followUpEmailSent: 'No',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'Yes',
    nutritionalAssesment: 'pending',
    remark: "Remarks about customer",
  },
  {
    id: 10,
    firstname: 'Toke',
    lastname: 'Akinde',
    email: 'Toke.Akinde@yahoo.com',
    username: 'Toke_Akinde',
    phone: '08158735782',
    createdAt: new Date("2021-05-02T12:30:00"),
    updatedAt: new Date(),
    promoCode: 'neo0010',
    customerPaid: 'Yes',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'missing',
    remark: "Remarks about customer",
  },
  {
    id: 11,
    firstname: 'Tosin',
    lastname: 'Adeola',
    email: 'Tosin.Adeola@gmail.com',
    username: 'Tosin_Adeola',
    phone: '08034987328',
    createdAt: new Date("2021-05-06T10:35:00"),
    updatedAt: new Date(),
    promoCode: 'neo0011',
    customerPaid: 'No',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'completed',
    remark: "Remarks about customer",
  },
  {
    id: 12,
    firstname: 'Tosin',
    lastname: 'Adeola',
    email: 'Tosin.Adeola@gmail.com',
    username: 'Tosin_Adeola',
    phone: '08034987328',
    createdAt: new Date("2021-05-06T10:35:00"),
    updatedAt: new Date(),
    promoCode: 'neo0012',
    customerPaid: 'No',
    followUpEmailSent: 'Yes',
    followUpCallSent: 'Yes',
    nutritionistScheduled: 'No',
    nutritionalAssesment: 'completed',
    remark: "Remarks about customer",
  }
];